routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//////////// CLIENTES ////////////////////////////////////
Route::resource('clientes','ClienteController');
Route::post('/clientes/create', 'ClienteController@store');
Route::put('/{id}', 'ClienteController@update');

/////////////Usuarios/////////////////////////
	Route::resource('usuarios','UsuarioController');
	Route::post('/usuarios/create', 'UsuarioController@store');
	Route::put('/{id}', 'UsuarioController@update');

/////////////////////////////////promociones/////////////////////////
Route::resource('promociones','PromocionController');
Route::post('/promociones/create', 'PromocionController@store');
Route::put('/{id}', 'PromocionController@update');
/////////////////////////////////actas/////////////////////////
Route::resource('actas','ActasController');
Route::post('/actas/create', 'ActasController@store');
Route::put('/{id}', 'ActasController@update');
/////////////////////////////////Alimentos/////////////////////////
Route::resource('alimento','AlimentoController');
Route::post('/alimento/create', 'AlimentoController@store');
Route::put('/{id}', 'AlimentoController@update');

/////////////////////////////////Ingresos/////////////////////////
Route::resource('ingresos','IngresosController');
Route::post('/ingresos/create', 'IngresosController@store');
Route::put('/{id}', 'IngresosController@update');

app/Alimento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alimento extends Model{
	//protected $hidden = ['created_at','updated_at'];
	protected $fillable = ['id','nombre','agua','azucar','hdec','lipidos','proteina','fibra','calcio','hierro','magnesio','fosforo','potasio','sodio','cobre','activo'];
	protected $table = 'alimento';
}

app/Http/Controllers/AlimentoController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Alimento;

class AlimentoController extends Controller{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $datos['alimentos_table'] = Alimento::orderBy('id','DESC')->get();
        return view('alimento.index')->with($datos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('alimento.create');        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        try {

            $alimento = new Alimento();
            $alimento->nombre = $request->nombre;
            $alimento->agua = $request->agua;
            $alimento->azucar=$request->azucar;            
            $alimento->hdec=$request->hdec;
            $alimento->lipidos = $request->lipidos;
            $alimento->proteina = $request->proteina;
            $alimento->fibra = $request->fibra;
            $alimento->calcio = $request->calcio;
            $alimento->hierro = $request->hierro;
            $alimento->magnesio = $request->magnesio;
            $alimento->fosforo = $request->fosforo;
            $alimento->potasio = $request->potasio;
            $alimento->sodio = $request->sodio;
            $alimento->cobre = $request->cobre;
            $alimento->save();
            return response()->json(['success'=>'Se ha Agegado con Exito']);
        } catch (Exception $e) {
            dd($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $datos['alimento'] = Alimento::find($id);
        return view('alimento.create')->with($datos);   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id){
        try {
            $alimento = Alimento::find($id);
            $alimento->fill($request->all());
            $alimento->save();
            return response()->json(['success'=>'Se ha Editado con Exito']);
        } catch (Exception $e) {
            dd($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){
        $alimento = Alimento::find($id);
        $alimento->delete();
        return redirect()->route('alimento.index');
    }
}

resources/views/alimento/create.blade.php
@extends('layouts.app')
@section('content')
<div class="col-md-12">
	<div class="box box-primary">
	    <div class="box-header with-border">
	    	@isset($alimento)
	    	<h3 class="box-title">Actualizar Alimento</h3>
			@else
			<h3 class="box-title">Nuevo Alimento</h3>
			@endisset
	    </div>
	    <!-- /.box-header -->
	    <!-- form start -->
	    <form role="form">
	      <div class="box-body">

	      	<div class="row">

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Nombre del Alimento</label>
			          <input type="text" class="form-control" name="nombre" placeholder="Nombre del Alimento" value="@isset($alimento){{ $alimento->nombre }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Agua</label>
			          <input type="number" step="0.01" class="form-control" name="agua" placeholder="Agua (g)" value="@isset($alimento){{ $alimento->agua }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Azucar</label>
			          <input type="number" step="0.01" class="form-control" name="azucar" placeholder="Azucar (g)" value="@isset($alimento){{ $alimento->azucar }}@endisset">
			        </div>
	      		</div>

	      	</div>

	      	<div class="row">

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Carbohidratos</label>
			          <input type="number" step="0.01" class="form-control" name="hdec" placeholder="Carbohidratos (g)" value="@isset($alimento){{ $alimento->hdec }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Lipidos</label>
			          <input type="number" step="0.01" class="form-control" name="lipidos" placeholder="Lipidos (g) " value="@isset($alimento){{ $alimento->lipidos }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Proteínas</label>
			          <input type="number" step="0.01" class="form-control" name="proteina" placeholder="Proteinas (g)" value="@isset($alimento){{ $alimento->proteinas }}@endisset">
			        </div>
	      		</div>


	      	</div>

	      	<div class="row">
	      		<div class="col-md-6">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Fibra</label>
			          <input type="number" step="0.01" class="form-control" name="fibra" placeholder="Fibra (g)" value="@isset($alimento){{ $alimento->fibra }}@endisset">
			        </div>

    	      	<div class="form-group">
					<label for="exampleInputPassword1">Calcio</label>
					<input type="number" step="0.01" class="form-control" name="calcio" placeholder="Calcio (mg)" value="@isset($alimento){{ $alimento->calcio }}@endisset">
			        </div>
	      		</div>


	      		<div class="col-md-6">
			        <div class="form-group">
						<label for="exampleInputPassword1">Hierro</label>
						<input type="number" step="0.01" class="form-control" name="hierro" placeholder="Hierro (mg)" value="@isset($alimento){{ $alimento->hierro }}@endisset">
			        </div>
			        <div class="form-group">
						<label for="exampleInputPassword1">Magnesio</label>
						<input type="number" step="0.01" class="form-control" name="magnesio" placeholder="Magnesio (mg)" value="@isset($alimento){{ $alimento->magnesio }}@endisset">
			        </div>
	      		</div>

	      	</div>

	      	<div class="row">
	      		<div class="col-md-6">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Fosforo</label>
			          <input type="number" step="0.01" class="form-control"  name="fosforo" placeholder="Fosforo (mg)" value="@isset($alimento){{ $alimento->fosforo }}@endisset">
			        </div>

    	      	<div class="form-group">
					<label for="exampleInputPassword1">Potasio</label>
					<input type="number" step="0.01" class="form-control" name="potasio" placeholder="Potasio (mg)" value="@isset($alimento){{ $alimento->potasio }}@endisset">
			        </div>
	      		</div>


	      		<div class="col-md-6">
			        <div class="form-group">
						<label for="exampleInputPassword1">Sodio</label>
						<input type="number" step="0.01" class="form-control" name="sodio" placeholder="Sodio (mg)" value="@isset($alimento){{ $alimento->sodio }}@endisset">
			        </div>
			        <div class="form-group">
						<label for="exampleInputPassword1">Cobre</label>
						<input type="number" step="0.01" class="form-control" name="cobre" placeholder="Cobre (mg)" value="@isset($alimento){{ $alimento->cobre }}@endisset">
			        </div>
	      		</div>
	      	</div>







	      </div>
	      <!-- /.box-body -->

	      <div class="box-footer">
	      	<a href="{{ url('alimento') }}" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Regresar</a>
	      	@isset($alimento)
	      	<button type="submit" class="btn btn-primary btn-submit"><i class="fa fa-repeat"></i> Actualizar</button>
	      	@else
	        <button type="submit" class="btn btn-primary btn-submit"><i class="fa fa-save"></i> Agregar</button>
	        @endisset
	      </div>
	    </form>
	  </div>
</div>

<script>
	$(document).ready( function () {


	    $(".btn-submit").click(function(e){
        e.preventDefault();

        var nombre = $("input[name=nombre]").val();
        var agua = $("input[name=agua]").val();
        var azucar = $("input[name=azucar]").val();
        var hdec = $("input[name=hdec]").val();
        var lipidos = $("input[name=lipidos]").val();
        var proteina = $("input[name=proteina]").val();
        var fibra = $("input[name=fibra]").val();
        var calcio = $("input[name=calcio]").val();
        var hierro = $("input[name=hierro]").val();
        var magnesio = $("input[name=magnesio]").val();
        var fosforo = $("input[name=fosforo]").val();
        var potasio = $("input[name=potasio]").val();
        var sodio = $("input[name=sodio]").val();
        var cobre = $("input[name=cobre]").val();

        if(nombre == '' || azucar == '' || agua == ''|| hdec == '' || lipidos == ''){
        	swal("Upss!", "Lo sentimos Campos Vacios", "warning");
        }else{
        	$.ajax({
	           type:"{{ ( isset($alimento) ? 'PUT' : 'POST' ) }}",
	           url:"{{ ( isset($alimento) ) ? '/alimento/' . $alimento->id : '/alimento/create' }}",
	           headers: {
				      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				     },
	           data:{
	           	nombre:nombre,
				agua:agua,
				azucar:azucar,
				hdec:hdec,
				lipidos:lipidos,
				proteina:proteina,
				fibra:fibra,
				calcio:calcio,
				hierro:hierro,
				magnesio:magnesio,
				fosforo:fosforo,
				potasio:potasio,
				sodio:sodio,
				cobre:cobre
	           },

	            success:function(data){
	                swal({title: "Felicidades!", text: data.success, type: "success"}, function(){ location.href ="{{ url('alimento') }}"; } );
	            }


	        });

        }

  });
});
</script>
@endsection

resources/views/alimento/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
  <!-- MAP & BOX PANE -->
  <div class="box box-primary">
    <div class="box-header with-border">
     
      <h3 class="box-title"><i class="fa fa-user"></i> Alimentos </h3>


      <div class="box-tools pull-right">
        <a href="{{ route('alimento.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Nuevo Alimento</a>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">

    	  <table id="example" class="display" style="width:100%">
	        <thead>
	          <tr align="center">
              <th>Nombre</th>
              <th>Agua</th>
              <th>Azucar</th>
              <th>Carbohitrados</th>
              <th>Lipidos</th>
              <th>Proteinas</th>
              <th>Fibra</th>
	            <th>Calcio</th>
              <th>Hierro</th>
              <th>Magenesio</th>
              <th>Fosforo</th>
              <th>Potasio</th>
              <th>Sodio</th>
              <th>Cobre</th>


	          </tr>
	        </thead>
	        <tbody>
	          @foreach ($alimentos_table as $alimentos)
                  <tr align="center">
                      <td>{{ $alimentos->nombre }}</td>
                      <td>{{ $alimentos->agua}}</td>
                      <td>{{ $alimentos->azucar}}</td>
                      <td>{{ $alimentos->hdec}}</td>
                      <td>{{ $alimentos->lipidos}}</td>
                      <td>{{ $alimentos->proteina}}</td>
                      <td>{{ $alimentos->fibra}}</td>
                      <td>{{ $alimentos->calcio}}</td>
                      <td>{{ $alimentos->hierro}}</td>
                      <td>{{ $alimentos->magnesio}}</td>
                      <td>{{ $alimentos->fosforo}}</td>
                      <td>{{ $alimentos->potasio}}</td>
                      <td>{{ $alimentos->sodio}}</td>
                      <td>{{ $alimentos->cobre}}</td>

                      <td >
                        <form action="{{ route('alimento.destroy',$alimentos->id )}}" method="POST">
                                      @csrf
                                      @method('DELETE')
                        <div class="btn-group">
                          <button type="button" class="btn btn-warning"><a href="{{ route('alimento.edit',$alimentos->id)}}" style="color:#fff;"><i class="fa fa-pencil"></i> Editar</a></button>
                          <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i> Eliminar</button>
                        </div>
                        </form>
                      </td>
                  </tr>
                @endforeach
	        </tbody>
	      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

</div>
<script>
  $(document).ready(function() {
      
      $('#example').DataTable({
    
    "scrollY": 300,
    "scrollX": true,
    "pagingType": "full_numbers",
   language: {
    processing:     "Tratamiento en curso...",
    search:         "Buscar&nbsp;:",
    lengthMenu:    "Mostrando _MENU_ registros por página",
    info:           "Mostrando página _START_ a _TOTAL_ Elementos",
    infoEmpty:      "No hay registros disponibles",
    infoFiltered:   "(Filtrado de _MAX_ registros totales)",
    infoPostFix:    "",
    loadingRecords: "Cargando...",
    zeroRecords:    "Ningun Resgistro",
    emptyTable:     "No hay datos disponibles por el momento.",
    paginate: {
        first:      "Primeramente",
        previous:   "Anteriormente",
        next:       "Siguiente",
        last:       "Ultimo"
    },
    aria: {
        sortAscending:  ": Activar para ordenar la columna en orden ascendente.",
        sortDescending: ": Activar para ordenar la columna en orden descendente."
    }
},
dom: 'B<"clear">lfrtip',
    buttons: [
        'colvis'
    ],
});
      
  } );
</script>
@endsection