routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//////////// CLIENTES ////////////////////////////////////
Route::resource('clientes','ClienteController');
Route::post('/clientes/create', 'ClienteController@store');
Route::put('/{id}', 'ClienteController@update');

/////////////Usuarios/////////////////////////
	Route::resource('usuarios','UsuarioController');
	Route::post('/usuarios/create', 'UsuarioController@store');
	Route::put('/{id}', 'UsuarioController@update');

/////////////////////////////////promociones/////////////////////////
Route::resource('promociones','PromocionController');
Route::post('/promociones/create', 'PromocionController@store');
Route::put('/{id}', 'PromocionController@update');
/////////////////////////////////actas/////////////////////////
Route::resource('actas','ActasController');
Route::post('/actas/create', 'ActasController@store');
Route::put('/{id}', 'ActasController@update');
/////////////////////////////////Alimentos/////////////////////////
Route::resource('alimento','AlimentoController');
Route::post('/alimento/create', 'AlimentoController@store');
Route::put('/{id}', 'AlimentoController@update');

/////////////////////////////////Ingresos/////////////////////////
Route::resource('ingresos','IngresosController');
Route::post('/ingresos/create', 'IngresosController@store');
Route::put('/{id}', 'IngresosController@update');

app/Clientes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clientes extends Model
{
	protected $hidden = ['created_at','updated_at'];
    protected $fillable = ['id','nombre','apellido_paterno','apellido_materno','correo_electronico','telefono','direccion','fecha_nacimiento','peso','activo'];
    protected $table = 'clientes';

    
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;


use App\Clientes; 
use App\User; 
use Mail;
use Session;
use App\Mail\SendEmail;


class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){

       $datos['clientes_table'] = Clientes::where([['activo','1']])->orderBy('id','DESC')->get();

        return view('clientes.index')->with($datos);
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        

        return view('clientes.create');        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            try {



                $clientes = new Clientes();
                $clientes->nombre = $request->nombre;
                $clientes->apellido_paterno = $request->apellido_paterno;
                $clientes->apellido_materno = $request->apellido_materno;
                $clientes->correo_electronico = $request->correo_electronico;
                $clientes->telefono = $request->telefono;
                $clientes->direccion = $request->direccion;
                $clientes->fecha_nacimiento = $request->fecha_nacimiento;
                $clientes->peso = $request->peso;
                $clientes->save();





                return response()->json(['success'=>'Se ha Agegado con Exito']);
            } catch (\Exception $e) {
              dd($e->getMessage());
            }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
     public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $datos['clientes'] = Clientes::find($id);
        return view('clientes.create')->with($datos);    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

        try {
            
            $clientes = Clientes::find($id);
            $clientes->fill($request->all());
            $clientes->save();
        
           return response()->json(['success'=>'Se ha Editado con Exito']);

        } catch (\Exception $e) {
          dd($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $clientes = Clientes::find($id);
        $clientes->activo = 0;
        $clientes->save();



        return redirect()->route('clientes.index');
    }






}

resources/views/clientes/create.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
	<div class="box box-success">
	    <div class="box-header with-border">
	    	@isset($clientes)
	    	<h3 class="box-title">Actualizar Cliente</h3>
			@else
			<h3 class="box-title">Nuevo Cliente</h3>
			@endisset
	    </div>
	    <!-- /.box-header -->
	    <!-- form start -->
	    <form role="form">
	      <div class="box-body">

	      	<div class="row">

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Nombre del Cliente</label>
			          <input type="text" class="form-control" name="nombre" placeholder="Nombre del Cliente" value="@isset($clientes){{ $clientes->nombre }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Apellido Paterno</label>
			          <input type="text" class="form-control" name="apellido_paterno" placeholder="Apellido Paterno" value="@isset($clientes){{ $clientes->apellido_paterno }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Apellido Materno</label>
			          <input type="text" class="form-control" name="apellido_materno" placeholder="Apellido Materno" value="@isset($clientes){{ $clientes->apellido_materno }}@endisset">
			        </div>
	      		</div>
	      		
	      	</div>

	      	<div class="row">

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Correo Electronico</label>
			          <input type="text" class="form-control" name="correo_electronico" placeholder="Correo Electronico" value="@isset($clientes){{ $clientes->correo_electronico }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Telefono</label>
			          <input type="text" class="form-control" name="telefono" placeholder="Telefono" value="@isset($clientes){{ $clientes->telefono }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-4">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Dirección</label>
			          <input type="text" class="form-control" name="direccion" placeholder="Dirección" value="@isset($clientes){{ $clientes->direccion }}@endisset">
			        </div>
	      		</div>


	      	</div>

	      	<div class="row">
	      		<div class="col-md-6">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Fecha de Nacimiento</label>
			          <input type="text" class="form-control" id="datepicker" name="fecha_nacimiento" placeholder="Fecha de Nacimiento" value="@isset($clientes){{ $clientes->fecha_nacimiento }}@endisset">
			        </div>
	      		</div>

	      		<div class="col-md-6">
	      			<div class="form-group">
			          <label for="exampleInputPassword1">Peso</label>
			          <input type="text" class="form-control" name="peso" placeholder="Peso del Cliente" value="@isset($clientes){{ $clientes->peso }}@endisset">
			        </div>
	      		</div>

	      	</div>

	        

	        

	        
	        
	      </div>
	      <!-- /.box-body -->

	      <div class="box-footer">
	      	<a href="{{ url('clientes') }}" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Regresar</a>
	      	@isset($clientes)
	      	<button type="submit" class="btn btn-success btn-submit"><i class="fa fa-repeat"></i> Actualizar</button>
	      	@else
	        <button type="submit" class="btn btn-success btn-submit"><i class="fa fa-save"></i> Agregar</button>
	        @endisset
	      </div>
	    </form>
	  </div>
</div>

<script>
	$(document).ready( function () {


	    $(".btn-submit").click(function(e){

	    
        e.preventDefault();

        var nombre = $("input[name=nombre]").val();
        var apellido_paterno = $("input[name=apellido_paterno]").val();
        var apellido_materno = $("input[name=apellido_materno]").val();
        var correo_electronico = $("input[name=correo_electronico]").val();
        var telefono = $("input[name=telefono]").val();
        var direccion = $("input[name=direccion]").val();
        var fecha_nacimiento = $("input[name=fecha_nacimiento]").val();
        var peso = $("input[name=peso]").val();




        if(nombre == '' || apellido_paterno == '' || correo_electronico == '' ){

        	
        	swal("Upss!", "Lo sentimos Campos Vacios", "warning");
        	

        }else{

        	$.ajax({

	           type:"{{ ( isset($clientes) ? 'PUT' : 'POST' ) }}",

	           url:"{{ ( isset($clientes) ) ? '/clientes/' . $clientes->id : '/clientes/create' }}",
	           headers: {
				      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				     },
	           data:{
				nombre:nombre,
				apellido_paterno:apellido_paterno,
				apellido_materno:apellido_materno,
				correo_electronico:correo_electronico,
				telefono:telefono,
				direccion:direccion,
				fecha_nacimiento:fecha_nacimiento,
				peso:peso,
	           },
	           
	            success:function(data){
	                swal({title: "Felicidades!", text: data.success, type: "success"}, function(){ location.href ="{{ url('clientes') }}"; } );
	            }


	        });

        }

  });
}); 
</script>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
  <!-- MAP & BOX PANE -->
  <div class="box box-success">
    <div class="box-header with-border">
     
      <h3 class="box-title"><i class="fa fa-user"></i> Clientes </h3>


      <div class="box-tools pull-right">
        <a href="{{ route('clientes.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Nuevo Cliente</a>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">

    	  <table id="example" class="display" style="width:100%">
	        <thead>
	          <tr align="center">
              <th>Nombre</th>
              <th>Apellido Paterno</th>
              <th>Apellido Materno</th>
              <th>Correo Electronico</th>
              <th>Telefono</th>
              <th>Fecha de Nacimiento</th>
              <th>Peso</th>
	            <th>Acciones</th>
	          </tr>
	        </thead>
	        <tbody>
	          @foreach ($clientes_table as $cliente)
                  <tr align="center">
                      <td>{{ $cliente->nombre }}</td>
                      <td>{{ $cliente->apellido_paterno }}</td>
                      <td>{{ $cliente->apellido_materno }}</td>
                      <td>{{ $cliente->correo_electronico }}</td>
                      <td>{{ $cliente->telefono }}</td>
                      <td>{{ $cliente->fecha_nacimiento }}</td>
                      <td>{{ $cliente->peso }} Kg</td>


                      <td >
                        <form action="{{ route('clientes.destroy',$cliente->id )}}" method="POST">
                                      @csrf
                                      @method('DELETE')
                        <div class="btn-group">
                          <button type="button" class="btn btn-warning"><a href="{{ route('clientes.edit',$cliente->id)}}" style="color:#fff;"><i class="fa fa-pencil"></i> Editar</a></button>
                          <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i> Eliminar</button>
                        </div>
                        </form>
                      </td>
                  </tr>
                @endforeach
	        </tbody>
	      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

</div>
<script>
  $(document).ready(function() {
      
      $('#example').DataTable({
    
    "scrollY": 300,
    "scrollX": true,
    "pagingType": "full_numbers",
   language: {
    processing:     "Tratamiento en curso...",
    search:         "Buscar&nbsp;:",
    lengthMenu:    "Mostrando _MENU_ registros por página",
    info:           "Mostrando página _START_ a _TOTAL_ Elementos",
    infoEmpty:      "No hay registros disponibles",
    infoFiltered:   "(Filtrado de _MAX_ registros totales)",
    infoPostFix:    "",
    loadingRecords: "Cargando...",
    zeroRecords:    "Ningun Resgistro",
    emptyTable:     "No hay datos disponibles por el momento.",
    paginate: {
        first:      "Primeramente",
        previous:   "Anteriormente",
        next:       "Siguiente",
        last:       "Ultimo"
    },
    aria: {
        sortAscending:  ": Activar para ordenar la columna en orden ascendente.",
        sortDescending: ": Activar para ordenar la columna en orden descendente."
    }
},
dom: 'B<"clear">lfrtip',
    buttons: [
        'colvis'
    ],
});
      
  } );
</script>
@endsection