routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//////////// CLIENTES ////////////////////////////////////
Route::resource('clientes','ClienteController');
Route::post('/clientes/create', 'ClienteController@store');
Route::put('/{id}', 'ClienteController@update');

/////////////Usuarios/////////////////////////
	Route::resource('usuarios','UsuarioController');
	Route::post('/usuarios/create', 'UsuarioController@store');
	Route::put('/{id}', 'UsuarioController@update');

/////////////////////////////////promociones/////////////////////////
Route::resource('promociones','PromocionController');
Route::post('/promociones/create', 'PromocionController@store');
Route::put('/{id}', 'PromocionController@update');
/////////////////////////////////actas/////////////////////////
Route::resource('actas','ActasController');
Route::post('/actas/create', 'ActasController@store');
Route::put('/{id}', 'ActasController@update');
/////////////////////////////////Alimentos/////////////////////////
Route::resource('alimento','AlimentoController');
Route::post('/alimento/create', 'AlimentoController@store');
Route::put('/{id}', 'AlimentoController@update');

/////////////////////////////////Ingresos/////////////////////////
Route::resource('ingresos','IngresosController');
Route::post('/ingresos/create', 'IngresosController@store');
Route::put('/{id}', 'IngresosController@update');

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

use App\User;

use Auth;
use Mail;
use Session;
use App\Mail\SendEmail;


class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       $datos['usuarios_table'] = User::where([['activo','1']])->orderBy('id','DESC')->get();

        return view('usuarios.index')->with($datos);
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        

        
        return view('usuarios.create');        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            try {


                    
                    $tienda = new User();
                    $tienda->name = $request->name;
                    $tienda->email = $request->email;
                    $tienda->password = bcrypt($request->password);
                    $tienda->password_name = $request->password;
                    $tienda->tipo_user = $request->tipo_user;
                    $tienda->save();
                


                    $email = $request->email;
                    $subject = 'Cuenta de Usuario';
                    $message = $request->email.','.$request->password;

                    Mail::to($email)->send( new SendEmail($subject,$message ));
                

                


                //return redirect()->route('usuarios.index');
                return response()->json(['success'=>'Se ha Agegado con Exito']);
            } catch (\Exception $e) {
              dd($e->getMessage());
            }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
     public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       
        $datos['usuarios'] = User::find($id);
       
         
        return view('usuarios.create')->with($datos);    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
            

        try {
            
            
                    $usuario = User::find($id);
                    $usuario->name = $request->name;
                    $usuario->email = $request->email;
                    $usuario->password = bcrypt($request->password);
                    $usuario->password_name = $request->password;
                    $usuario->tipo_user = $request->tipo_user;
                    $usuario->save();
                
                    return response()->json(['success'=>'Se ha Editado con Exito']);

                    $email = $request->email;
                    $subject = 'Actualizacion de Password';
                    $message = $request->email.','.$request->password;

                    Mail::to($email)->send( new SendEmail($subject,$message ));
                    

           

        } catch (\Exception $e) {
          dd($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tienda = User::find($id);
        $tienda->activo = 0;
        $tienda->save();


        return redirect()->route('usuarios.index');
    }





    






}

resources/views/usuarios/create.blade.php
@extends('layouts.app')

@section('content')
<style type="text/css" media="screen">
.select2-container--default .select2-selection--multiple .select2-selection__choice {
background-color: 
#3c8dbc;
border-color:
#367fa9;
padding: 1px 10px;
color:
    #fff;
}
.my-custom-scrollbar {
position: relative;
height: 200px;
overflow: auto;
}
.table-wrapper-scroll-y {
display: block;
}
</style>
<div class="col-md-12">
	<div class="box box-success">
	    <div class="box-header with-border">
	    	@isset($usuarios)
	    	<h3 class="box-title">Actualizar Usuario</h3>
			@else
			<h3 class="box-title">Nuevo Usuario</h3>
			@endisset
	    </div>
	    <!-- /.box-header -->
	    <!-- form start -->


	        <form >

	      <div class="box-body">
	      	<div class="col-md-6">
	      	<div class="form-group">
	          <label for="exampleInputPassword1">Nombre del Usuario</label>
	          <input type="text" class="form-control" name="name" placeholder="Nombre de Articulo" value="@isset($usuarios){{ $usuarios->name }}@endisset">
	        </div>
	    	</div>
	    	<div class="col-md-6">
		        <div class="form-group">
		          <label for="exampleInputEmail1">Correo Electronico</label>
		          <input type="text" class="form-control" name="email" placeholder="Correo Electronico" value="@isset($usuarios){{ $usuarios->email }}@endisset">
		        </div>
	    	</div>
	    	<div class="col-md-6">
		        <div class="form-group">
		          <label for="exampleInputPassword1">Password</label>
		          <input type="text" class="form-control" name="password" placeholder="Password" value="@isset($usuarios){{ $usuarios->password_name }}@endisset">
		        </div>
		    </div>

		    

	        <div class="col-md-6">
              	<div class="form-group">
	                <label>Tipo de Usuario</label>
	                <select class="form-control select2 " style="width: 100%;"  name="tipo_user" tabindex="-1" aria-hidden="true">
	                 <option >Elige una Oción de Usuario</option>
	                 <option value="1">Administrador</option>
	                 <option value="2">Usuario</option>
	                </select>
            	</div>
              
            </div>
            

	      </div>
	      <!-- /.box-body -->

	      <div class="box-footer">
	      	<a href="{{ url('usuarios') }}" ><button type="button" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Regresar</button></a>
	      	@isset($usuarios)
	      	<button type="submit" class="btn btn-success btn-submit"><i class="fa fa-repeat"></i> Actualizar</button>
	      	@else
	        <button type="submit" class="btn btn-success btn-submit"><i class="fa fa-save"></i> Agregar</button>
	        @endisset
	      </div>
	    </form>
	  </div>
</div>



<script>

	$(document).ready( function () {



		$(".btn-submit").click(function(e){
        e.preventDefault();
        ////////// limpieza

        var name = $('input[name=name]').val();
        var email = $('input[name=email]').val();
        var password = $('input[name=password]').val();
        var tipo_user = $('select[name=tipo_user]').val();


        if(name == ' ' || email == ' ' || password == ' ' || tipo_user == ' '  ){
        	swal({title: "Cuidado!", text: "No Existen Permisos Nuevos", type: "warning"}, function(){ } );
        }else{
        	$.ajax({

	           type:"{{ ( isset($usuarios) ? 'PUT' : 'POST' ) }}",

	           url:"{{ ( isset($usuarios) ) ? '/usuarios/' . $usuarios->id : '/usuarios/create' }}",
	           headers: {
				      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				     },
	           data:{
				name:name,
				email:email,
				password:password,
				tipo_user:tipo_user,
				
	           },
	           
	            success:function(data){
	                swal({title: "Felicidades!", text: data.success, type: "success"}, function(){ location.href ="{{ url('usuarios') }}"; } );
	            }


	        });
        }


        	

       
        });
	    
}); 


	
</script>
@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
  <!-- MAP & BOX PANE -->
  <div class="box box-success">
    <div class="box-header with-border">
      
      <h3 class="box-title"><i class="fa fa-users"></i> Usuarios  </h3>


      <div class="box-tools pull-right">
        <a href="{{ route('usuarios.create') }}" class="btn btn-success"> Nuevo Usuario</a>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">

    	  <table id="example" class="display" style="width:100%">
	        <thead>
	          <tr align="center">
              <th>Nombre de Usuario</th>
	            <th>Correo Electronico</th>
	            <th>Password</th>
	            <th>Tipo de Usuario</th>
	            <th>Acciones</th>
	          </tr>
	        </thead>
	        <tbody>
	          @foreach ($usuarios_table as $usuario)
                  <tr align="center">
                      <td>{{ $usuario->name }}</td>
                      <td>{{ $usuario->email }}</td>
                      <td>{{ $usuario->password_name }}</td>
                      <td><?php 
                        if ($usuario->tipo_user == 1) {
                          echo 'Administrador';
                        }else{
                          echo 'Usuario';
                        }
                        ?></td>
                      <td >
                        <form action="{{ route('usuarios.destroy',$usuario->id )}}" method="POST">
                                      @csrf
                                      @method('DELETE')
                        <div class="btn-group">
                          <button type="button" class="btn btn-warning"><a href="{{ route('usuarios.edit',$usuario->id)}}" style="color:#fff;"><i class="fa fa-pencil"></i> Editar</a></button>
                            <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i> Eliminar</button>
                        </div>
                        </form>
                      </td>
                  </tr>
                @endforeach
	        </tbody>
	      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

</div>
<script>
  $(document).ready(function() {
      
      $('#example').DataTable({
    
    "scrollY": 300,
    "scrollX": true,
    "pagingType": "full_numbers",
   language: {
    processing:     "Tratamiento en curso...",
    search:         "Buscar&nbsp;:",
    lengthMenu:    "Mostrando _MENU_ registros por página",
    info:           "Mostrando página _START_ a _TOTAL_ Elementos",
    infoEmpty:      "No hay registros disponibles",
    infoFiltered:   "(Filtrado de _MAX_ registros totales)",
    infoPostFix:    "",
    loadingRecords: "Cargando...",
    zeroRecords:    "Ningun Resgistro",
    emptyTable:     "No hay datos disponibles por el momento.",
    paginate: {
        first:      "Primeramente",
        previous:   "Anteriormente",
        next:       "Siguiente",
        last:       "Ultimo"
    },
    aria: {
        sortAscending:  ": Activar para ordenar la columna en orden ascendente.",
        sortDescending: ": Activar para ordenar la columna en orden descendente."
    }
},

});
      
  } );
</script>
@endsection